[versions]
axon-extensions-reactor = "4.12.0"
axon-micrometer = "4.12.2"
axon-spring-boot-starter = "4.12.2"
com-github-ben-manes-versions = "0.53.0"
com-google-devtools-ksp = "2.3.1"
io-axoniq-console-framework-client-spring-boot-starter = "1.10.1"
io-kotest = "6.0.4"
io-micrometer-micrometer-observation-test = "1.15.5"
io-micrometer-micrometer-tracing-test = "1.5.5"
io-mockk = "1.14.6"
io-spring-dependency-management = "1.1.7"
jackson-module-kotlin = "2.20.1"
jakarta-validation-api = "3.1.1"
kotlin-logging-jvm = "7.0.13"
kotlinx-coroutines-reactor = "1.10.2"
micrometer-registry-prometheus = "1.15.5"
micrometer-tracing-bridge-brave = "1.5.5"
nl-littlerobots-version-catalog-update = "1.0.1"
org-jetbrains-kotlin = "2.2.21"
org-jlleitschuh-gradle-ktlint = "13.1.0"
org-springframework-boot = "3.5.7"
reactor-kotlin-extensions = "1.2.4"
reactor-test = "3.7.12"
snakeyaml = "2.5"
zipkin-reporter-brave = "3.5.1"

[libraries]
com-fasterxml-jackson-module-jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson-module-kotlin" }
com-google-devtools-ksp-symbol-processing-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "com-google-devtools-ksp" }
io-axoniq-console-framework-client-spring-boot-starter = { module = "io.axoniq.console:console-framework-client-spring-boot-starter", version.ref = "io-axoniq-console-framework-client-spring-boot-starter" }
io-github-oshai-kotlin-logging-jvm = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging-jvm" }
io-kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "io-kotest" }
io-kotest-property = { module = "io.kotest:kotest-property", version.ref = "io-kotest" }
io-kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "io-kotest" }
io-micrometer-observation-test = { module = "io.micrometer:micrometer-observation-test", version.ref = "io-micrometer-micrometer-observation-test" }
io-micrometer-registry-prometheus = { module = "io.micrometer:micrometer-registry-prometheus", version.ref = "micrometer-registry-prometheus" }
io-micrometer-tracing-bridge-brave = { module = "io.micrometer:micrometer-tracing-bridge-brave", version.ref = "micrometer-tracing-bridge-brave" }
io-micrometer-tracing-test = { module = "io.micrometer:micrometer-tracing-test", version.ref = "io-micrometer-micrometer-tracing-test" }
io-mockk = { module = "io.mockk:mockk", version.ref = "io-mockk" }
io-projectreactor-kotlin-reactor-kotlin-extensions = { module = "io.projectreactor.kotlin:reactor-kotlin-extensions", version.ref = "reactor-kotlin-extensions" }
io-projectreactor-reactor-test = { module = "io.projectreactor:reactor-test", version.ref = "reactor-test" }
io-zipkin-reporter2-zipkin-reporter-brave = { module = "io.zipkin.reporter2:zipkin-reporter-brave", version.ref = "zipkin-reporter-brave" }
jakarta-validation-api = { module = "jakarta.validation:jakarta.validation-api", version.ref = "jakarta-validation-api" }
org-axon-extensions-reactor-spring-boot-starter = { module = "org.axonframework.extensions.reactor:axon-reactor-spring-boot-starter", version.ref = "axon-extensions-reactor" }
org-axon-micrometer = { module = "org.axonframework:axon-micrometer", version.ref = "axon-micrometer" }
org-axon-spring-boot-starter = { module = "org.axonframework:axon-spring-boot-starter", version.ref = "axon-spring-boot-starter" }
org-jetbrains-kotlin-kotlin-reflect = "org.jetbrains.kotlin:kotlin-reflect:2.2.21"
org-jetbrains-kotlin-kotlin-stdlib-jdk8 = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:2.2.21"
org-jetbrains-kotlinx-kotlinx-coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version.ref = "kotlinx-coroutines-reactor" }
org-springframework-boot-spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
org-springframework-boot-spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
org-springframework-boot-spring-boot-testcontainers = { module = "org.springframework.boot:spring-boot-testcontainers" }
org-yaml-snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }

[plugins]
com-github-ben-manes-versions = { id = "com.github.ben-manes.versions", version.ref = "com-github-ben-manes-versions" }
com-google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "com-google-devtools-ksp" }
io-spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "io-spring-dependency-management" }
nl-littlerobots-version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "nl-littlerobots-version-catalog-update" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-plugin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "org-jetbrains-kotlin" }
org-jetbrains-kotlin-plugin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "org-jetbrains-kotlin" }
org-jlleitschuh-gradle-ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "org-jlleitschuh-gradle-ktlint" }
org-springframework-boot = { id = "org.springframework.boot", version.ref = "org-springframework-boot" }
